version: 2

models:
  - name: classification_model
    descripton: This table stores the pickled model that is trained

  - name: model_predictions
    descripton: This table stores the batch predictions
